name: BLE_Examples_Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# allow a single workflow to run at any given time given that these tests 
# require the use of hardware devices
# second instance of a workflow will wait on the frist to finish
# third instance cancels the second instance and waits on the first to finish
concurrency:
  group: ble_examples_testing
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, btm-ci-github-runner-max32655]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: false 

      # Runs a set of commands using the runners shell
      - name: Build all BLE examples
        run: |
          cp -r /home/btm-ci/Workspace/BLE-examples-test/Examples_tests .
          chmod +x Examples_tests/local_testLauncher.sh
          cd Examples_tests/
          ./local_testLauncher.sh
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
            name: failure-report
            path: Examples_tests/results/

